### ISSUE TITLE
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by GraceZhuuu** [dizcza/sparse-representation#1]
When i tried the demo `python sparse/examples/basis_pursuit_pytorch.py`, the error occurred 
```
> python sparse/examples/basis_pursuit_pytorch.py                                                         
Checkpoint '/home/j/.cache/mighty/checkpoints/2023.11.27 MatchingPursuit: MNIST TrainMatchingPursuit Lo
ssPenalty(MSELoss).pt' doesn't exist. Nothing to restore.                                                 
MatchingPursuit(                                                                                          
  in_features=784, out_features=256                                                                       
  (solver): BasisPursuitADMM(lambd=0.1, tol=0.0001, max_iters=100)                                        
)                                                                                                         
Setting up a new session...                                                                               
Monitor is opened at http://localhost:8097. Choose environment '2023.11.27 MatchingPursuit: MNIST TrainMat
chingPursuit LossPenalty(MSELoss)'. 
Traceback (most recent call last):                                                                        
  File "/home/june/projects/sparse/sparse-representation/sparse/examples/basis_pursuit_pytorch.py", line 1
14, in <module>                                                                                           
    train_lista()                                                                                         
  File "/home/june/projects/sparse/sparse-representation/sparse/examples/basis_pursuit_pytorch.py", line 9
1, in train_lista                                                                                         
    model_ref = train_matching_pursuit(dataset_cls=dataset_cls)                                           
  File "/home/june/projects/sparse/sparse-representation/sparse/examples/basis_pursuit_pytorch.py", line 8
6, in train_matching_pursuit                                                                              
    trainer.train(n_epochs=n_epochs, mutual_info_layers=0)                                                
  File "/home/june/anaconda3/envs/sparse/lib/python3.9/site-packages/mighty/trainer/trainer.py", line 624,
 in train                                                                                                 
    self.train_epoch(epoch=epoch)                                                                         
  File "/home/june/anaconda3/envs/sparse/lib/python3.9/site-packages/mighty/trainer/trainer.py", line 520,
 in train_epoch                                                                                           
    loss = self.train_batch(batch)
  File "/home/june/anaconda3/envs/sparse/lib/python3.9/site-packages/mighty/trainer/gradient.py", line 73, in train_batch
    outputs = self._forward(batch)
  File "/home/june/anaconda3/envs/sparse/lib/python3.9/site-packages/mighty/trainer/trainer.py", line 360, in _forward
    return self.model(input)
  File "/home/june/anaconda3/envs/sparse/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/june/projects/sparse/sparse-representation/sparse/nn/model.py", line 97, in forward
    z = solver.solve(A=self.weight.t(), b=x)
  File "/home/june/projects/sparse/sparse-representation/sparse/nn/solver.py", line 134, in solve
    v_solution, dv_norm, iteration = basis_pursuit_admm(
  File "/home/june/projects/sparse/sparse-representation/sparse/nn/solver.py", line 105, in basis_pursuit_admm
    v, u, A_dot_b = _reduce(solved, solved_batch, v_solution, v, u,
  File "/home/june/projects/sparse/sparse-representation/sparse/nn/solver.py", line 34, in _reduce
    became_solved_ids = unsolved_ids[keys]
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

```
There are 2 gpus in Ubuntu system.
but i modify `use_cuda = False`, the error occurred again.
There may be some device control mistake.

**Comment by dizcza** [comment]
yeah, my projects don't support multi-GPU features.

Simply set `CUDA_VISIBLE_DEVICES=0` env in the command line prior launching the script:

```
CUDA_VISIBLE_DEVICES=0 python sparse/examples/basis_pursuit_pytorch.py
```

**Comment by GraceZhuuu** [comment]
> yeah, my projects don't support multi-GPU features.
> 
> Simply set `CUDA_VISIBLE_DEVICES=0` env in the command line prior launching the script:
> 
> ```
> CUDA_VISIBLE_DEVICES=0 python sparse/examples/basis_pursuit_pytorch.py
> ```

single-GPU didn't work neither, 
but set CUDA_VISIBLE_DEVICES="" (empty), it worked in CPUs.

**Comment by dizcza** [comment]
All right, I'll have a look at why it doesn't work on single-GPU devices.

**Comment by GraceZhuuu** [comment]
> All right, I'll have a look at why it doesn't work on single-GPU devices.

I got the problem !
```
def _reduce(solved, solved_batch, x_solution, x, *args):
    if solved_batch.any():
        args_reduced = []
        unsolved_ids = torch.nonzero(~solved, as_tuple=False)
        unsolved_ids.squeeze_(dim=1)
        keys = solved_batch.nonzero(as_tuple=False)
        keys.squeeze_(dim=1)
        # print(keys.device)
        # print(unsolved_ids.device)
        became_solved_ids = unsolved_ids[keys]
        x_solution[became_solved_ids] = x[keys]
        solved[became_solved_ids] = True
        mask_unsolved = ~solved_batch
        x = x[mask_unsolved]
        args_reduced.append(x)
        for arg in args:
            arg = arg[mask_unsolved]
            args_reduced.append(arg)
    else:
        args_reduced = [x, *args]
    return args_reduced
```
the `key` is in CUDA, but the `unsolved_ids` is in CPU.
(sorry for that i don't get a graceful PR, i moved `unsolved_ids.to('cuda')` that works.)

**Comment by dizcza** [comment]
Yes, the fix is rather simple, thanks.

**Comment by dizcza** [comment]
Your approach would break CPU implementation, I pushed a fix to the master branch.
